# Mabel Zhang
# 7 Oct 2018
#
# Path constants, to be read by both Python and C++.
#


root: /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping

# Subdirectories under root
data: data

# Text files under data/renders - these are defined in
#   depth_scene_rendering config_paths.py, used by scene_generation.py,
#   which cannot import yaml library because it needs to be run in Blender.
#   So it cannot read this file.
#   Read these paths from depth_scene_rendering/config/cam_config_path.txt,
#   written by scene_generation.py.
#intrinsics: intrinsics.txt
#depth_range: cam_depth_range.txt
# Directories under root/data

renders: renders
heatmaps: heatmaps
grasps: grasps
contacts: contacts
energies: energies

# Subdirectories under root
test_renders: test_renders
vis: vis


# Energy measure. Defined in grasp_collection config_consts.py. Pick the one
#   you want to generate data for.
energy_abbrev: gpqe

