objects:
- id: 0
  name: bar_clamp
- id: 1
  name: gearbox
- id: 2
  name: nozzle
- id: 3
  name: part1
- id: 4
  name: part3
- id: 5
  name: pawn
- id: 6
  name: turbine_housing
- id: 7
  name: vase
