objects:
  - object: bar_clamp
    id: 0
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-00-28_n.pcd
  - object: gearbox
    id: 1
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-01-53_n.pcd
  - object: nozzle
    id: 2
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-02-51_n.pcd
  - object: part1
    id: 3
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-03-47_n.pcd
  - object: part3
    id: 4
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-05-47_n.pcd
  - object: pawn
    id: 5
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-07-07_n.pcd
  - object: turbine_housing
    id: 6
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-07-35_n.pcd
  - object: vase
    id: 7
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/renders/2018-11-18-07-08-36_n.pcd
