objects:
  - object: gearbox
    scenes:
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/2018-10-09-05-22-54.pcd
    - /media/master/Data_Ubuntu/courses/research/graspingRepo/train/visuotactile_grasping/data/2018-10-09-05-23-01.pcd
